### ISSUE TITLE
Create xUnit based report

### ISSUE THREAD

**Issue by lopidio** [lopidio/enqueuer#43]
Add a XUnit like output in configuration file:
```
#optional
outputs:
-   type: file
    format: xunit
    filename: outputExamples/xunitReport.xml
```
